### ISSUE TITLE
FASTQ to (unaligned) BAM/SAM/CRAM

### ISSUE THREAD

**Issue by Midnighter** [stjude-rust-labs/fq#26]
Hi again 😄

I was wondering if a conversion utility from FASTQ to (unaligned) BAM/SAM/CRAM is something you had thought about and is in scope for this project? The alternative tools that I know for doing this ([picard](https://broadinstitute.github.io/picard/) and [fgbio](https://fulcrumgenomics.github.io/fgbio/)) are both big collections with huge dependencies so it would be nice to have a slim Rust-based tool for doing so. (I realize that this request might make fq less slim and add more dependencies.)

Thanks for your thoughts.

**Comment by Midnighter** [comment]
Did some more digging and it seems like either https://docs.rs/rust-htslib/latest/rust_htslib/ or https://docs.rs/crate/noodles/latest could be used for this. Didn't find a CLI yet, though.

**Comment by claymcleod** [comment]
Hey @Midnighter,

Good suggestion! This is missing from our current repertoire. We have a tool coming out in the near-ish future that might be a better home for this functionality (I really want this tool to be focused on FASTQ files specifically, but the new tool will cross between different file types).

Also, just a note, the author of noodles is actually the main author of this tool too. So we'd probably go with that library 😀

**Comment by Midnighter** [comment]
It's great to hear that you're thinking about it and that there might be a tool coming out in a bit. Feel free to ping me if you need some early testing done. I will also be happy to add a bioconda recipe for the new tool.
