### ISSUE TITLE
Feature request: Filtering based on reads

### ISSUE THREAD

**Issue by rorynolan** [stjude-rust-labs/fq#27]
I would love to be able to filter based on reads e.g. keep only reads starting with "GC". 
Would be cool to be able to do this by regex.

Thank you for your work. I am a user of `fq lint` and `fq subsample`.

**Comment by claymcleod** [comment]
> Thank you for your work. I am a user of `fq lint` and `fq subsample`.

That's great! Thanks for letting us know.

What do you think, @zaeleus?
