### ISSUE TITLE
Docs typo

### ISSUE THREAD

**Issue by rorynolan** [stjude-rust-labs/fq#28]
`-r, --record-count <RECORD_COUNT>`
should be `-n, --record-count <RECORD_COUNT>` right?
Elsewhere in the README, `-n` is mentioned.

**Comment by zaeleus** [comment]
Good catch, thanks! That bug was introduced when the argument parser was updated in e7625cf4b4e477a9ecc1fd01d64b56e2c1a10ae0. It's now fixed in 7288f2a225e831e99626a3325e2ee8161085c80d.
