### ISSUE TITLE
commands/filter: Apply filter rule to multiple segments

### ISSUE THREAD

**Issue by zaeleus** [stjude-rust-labs/fq#30]
Currently, the `filter` command only works on one input and writes a single output to stdout. It should also work with multiple segments and write multiple filtered outputs.

This was suggested by @rorynolan in https://github.com/stjude-rust-labs/fq/pull/29#issuecomment-1423001869.

**Comment by rorynolan** [comment]
Thanks a lot for this addition @zaeleus 
It is working well for me.
Maybe time for a new release? Would be nice to be able to install the filtering from conda.
