### ISSUE TITLE
Minor Change in fq lint README

### ISSUE THREAD

**Issue by SaimMomin12** [stjude-rust-labs/fq#32]
I recently figured out a minor misspelt flag in fq lint README

https://github.com/stjude-rust-labs/fq#validators
The README for Validator section states:

**"Validate includes a set of validators that run on single or paired records. By default, records are validated with all rules, but validators can be disabled using `--disable-valdiator` CODE, where CODE is one of validators listed below."**

Here, the `--disable-valdiator` flag is misspelled and needs to corrected to `--disable-validator` to avoid inconvenience to new users. 

Cheers!

**Comment by zaeleus** [comment]
Thanks!
